[platformio]
default_envs = esp32_ds3231

[env]
platform = platformio/espressif32@6.7.0
board = esp32dev
framework = arduino
lib_extra_dirs = ../..
lib_deps =
  Preferences
  Wire
  symlink://../..
build_flags =
  -D ESP32BASE_PROFILE=ESP32BASE_PROFILE_CORE
  -D ESP32BASE_ENABLE_RTC=1
  -D ESP32BASE_DEFAULT_HOSTNAME=\"esp32base-rtc\"

[env:esp32_ds3231]
build_flags =
  ${env.build_flags}
  -D ESP32BASE_RTC_DRIVER=ESP32BASE_RTC_DRIVER_DS3231

[env:esp32_pcf8563]
build_flags =
  ${env.build_flags}
  -D ESP32BASE_RTC_DRIVER=ESP32BASE_RTC_DRIVER_PCF8563
