#include "../../Esp32BaseProfile.h"

#if ESP32BASE_ENABLE_WEB

#include "WebInternal.h"

namespace esp32base_web {

#ifndef ESP32BASE_WEB_CSS_VERSION
#define ESP32BASE_WEB_CSS_VERSION __TIME__
#endif

const char WEB_CSS_TYPE[] PROGMEM = "text/css; charset=utf-8";
const char WEB_CSS[] PROGMEM =
    ":root{color-scheme:light;--eb-bg:#f6f8fa;--eb-surface:#fff;--eb-soft:#f8fafb;--eb-ink:#17202a;--eb-muted:#667085;--eb-line:#d7dde4;--eb-line-soft:#edf1f4;--eb-primary:#176b7a;--eb-primary-hover:#125965;--eb-primary-soft:#e8f3f5;--eb-button-soft:#f7fafb;--eb-button-soft-hover:#eef4f6;--eb-button-border:#d9e5ea;--eb-ok:#087443;--eb-ok-soft:#e7f4ee;--eb-warn:#9a5a0a;--eb-warn-soft:#fff6e8;--eb-danger:#ad3027;--eb-danger-hover:#982a22;--eb-danger-soft:#fff4f2;--eb-info:#356783;--eb-info-soft:#edf4f7}"
    "*{box-sizing:border-box}body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Arial,sans-serif;font-size:14px;line-height:1.42;margin:0;padding:12px 14px 36px;color:var(--eb-ink);background:var(--eb-bg);max-width:1180px;margin-inline:auto}"
    "h1,h2,h3{color:#111827;line-height:1.25;margin:0 0 8px}h1{font-size:18px}h2{font-size:16px}h3{font-size:15px}p{margin:0 0 9px}"
    "a{color:#25313f;text-decoration:none}.muted,.info{color:var(--eb-muted)}.ok{color:var(--eb-ok)}.err,.dangertext{color:var(--eb-danger)}"
    "nav,.panel,.footerbar,.pagehead{background:var(--eb-surface);border:1px solid var(--eb-line);border-radius:8px;box-shadow:0 1px 2px rgba(16,24,40,.04)}"
    "nav{display:flex;align-items:center;gap:4px;overflow:auto;white-space:nowrap;margin:0 0 12px;padding:3px}.brand{font-weight:800}nav a{display:inline-flex;align-items:center;min-height:34px;padding:0 11px;margin:0;border-radius:6px;color:#344054;font-size:14px;font-weight:750}nav a.active{background:var(--eb-primary-soft);color:var(--eb-primary)}"
    ".page{margin:0}.pagehead{padding:11px 12px;margin:0 0 12px}.pagehead h1{margin:0}.pagehead p{margin:4px 0 0;color:var(--eb-muted);font-size:13px}.panel{padding:12px;margin:12px 0}.panel>:last-child{margin-bottom:0}.actions,.filterbar{display:flex;flex-wrap:wrap;gap:8px;align-items:center;margin-top:10px}.filterbar{margin:0 0 10px}.filterbar label{margin:0;color:var(--eb-muted);font-size:13px}.filterbar select,.filterbar input{width:auto;margin:0}.editform{max-width:760px}.fieldgrid{display:grid;grid-template-columns:repeat(12,minmax(0,1fr));gap:10px 12px;align-items:start}.field{margin:0}.field input,.field select{margin:0}.field.short{grid-column:span 2}.field.med{grid-column:span 4}.field.long{grid-column:span 6}.field.full{grid-column:1/-1;max-width:720px}.field small{display:block;margin-top:4px;color:var(--eb-muted);font-size:12px}.tablewrap{overflow-x:auto;margin:0}"
    ".formpanel form,.actionpanel form,.dangerpanel form{max-width:760px}.formpanel .fieldgrid{margin:0}.authpanel .field.med{grid-column:span 6}.formpanel .kv,.actionpanel .kv{font-size:13px}.formpanel .kv th,.actionpanel .kv th{width:176px;max-width:38%}.dangerpanel{border-color:#ebb8b2;background:#fffafa}.dangerpanel h2{color:#84251f}.dangerpanel .dangertext{margin-bottom:8px}.uploadpanel progress{margin-top:10px}.radioopts label{display:inline-flex;align-items:center;gap:5px;margin:0 10px 6px 0;font-weight:500}.radioopts input{margin:0}"
    "button,input[type=submit],input[type=button]{font-size:14px;background:var(--eb-primary);color:#fff;min-height:30px;padding:0 10px;border:1px solid transparent;border-radius:6px;cursor:pointer;margin:0;font-weight:650;line-height:1.1}button:hover,input[type=submit]:hover,input[type=button]:hover{background:var(--eb-primary-hover)}button:disabled,input[type=submit]:disabled,input[type=button]:disabled{opacity:.62;cursor:default}.secondary,input.secondary{background:var(--eb-button-soft);color:#344054;border:1px solid var(--eb-button-border)}.secondary:hover,input.secondary:hover{background:var(--eb-button-soft-hover)}.dangerbtn,input.danger{background:var(--eb-danger-soft);color:var(--eb-danger);border:1px solid #efc0ba}.dangerbtn:hover,input.danger:hover{background:#ffe8e4;color:var(--eb-danger-hover)}"
    "label{display:block;font-weight:700;margin:0 0 4px}input:not([type]),input[type=text],input[type=password],input[type=number],input[type=email],input[type=url],input[type=tel],input[type=search],select{font-size:14px;min-height:32px;padding:6px 9px;margin:0 0 10px;border:1px solid #ccd5dd;border-radius:7px;background:#fff;color:#1f2933}"
    "input:not([type]),input[type=text],input[type=password],input[type=email],input[type=url],input[type=tel],input[type=search]{width:100%}input[type=number]{max-width:14ch}select{max-width:260px}"
    "input[type=file]{font-size:14px;margin:2px 0 12px;max-width:100%}progress{height:12px;border:0;border-radius:8px;overflow:hidden;background:#e7ebef}"
    "details{margin:12px 0}summary{cursor:pointer;color:#25313f}.footerbar{margin-top:10px;padding:5px 8px;display:flex;flex-wrap:wrap;align-items:center;justify-content:space-between;gap:8px;color:var(--eb-muted);font-size:12px;border-color:var(--eb-line-soft);border-radius:6px;box-shadow:none}"
    ".syslinks{min-width:0;flex:1 1 auto;display:flex;flex-wrap:wrap;gap:4px;align-items:center}.syslinks a{display:inline-flex;align-items:center;min-height:24px;font-size:12px;line-height:1.25;padding:0 6px;margin:0;background:#f3f5f5;color:var(--eb-muted);border-radius:4px}.heap{flex:0 0 auto;margin-left:auto;white-space:nowrap;text-align:right;font-size:11px}"
    ".notice{border:1px solid var(--eb-line);background:var(--eb-soft);border-radius:8px;padding:9px 10px;margin:8px 0;color:var(--eb-ink)}.notice.ok{border-color:#bfe0d4;background:var(--eb-ok-soft);color:#185b4e}.notice.warn{border-color:#efcf96;background:var(--eb-warn-soft);color:#7a4608}.notice.danger{border-color:#ebb8b2;background:var(--eb-danger-soft);color:#84251f}.notice.info{border-color:#c6d7ea;background:var(--eb-info-soft);color:var(--eb-info)}"
    ".toolgrid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px;margin:12px 0}.toolgrid .panel{margin:0}.toollinks{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.toollinks .urow{padding:8px;border:1px solid var(--eb-line-soft);border-radius:7px;background:#fff}.toollinks .urow:last-child{border-bottom:1px solid var(--eb-line-soft)}.toollinks .uactions{grid-template-columns:72px;gap:0}.toollinks .uactions .uvalue{display:none}.toollinks .uactions .btnlink{min-width:72px;width:72px;min-height:30px}.hostfacts{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:4px 10px;margin:4px 0 8px;font-size:13px}.hostfacts span{min-width:0;overflow-wrap:anywhere}.hostfacts b{display:inline-block;min-width:5.8em;margin-right:4px;color:var(--eb-muted);font-weight:650}.hostedit{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:8px;align-items:end;max-width:760px;margin-top:8px}.hostedit .field{min-width:0}.hostedit .actions{margin:0}"
    ".metrics{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:8px;margin:8px 0}.metric{border:1px solid var(--eb-line-soft);border-radius:7px;background:#fff;padding:8px}.metric b{display:block;font-size:17px}.metric span{display:block;color:var(--eb-muted);font-size:12px}"
    ".statusgrid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px;align-items:start}.statusgrid .panel{margin:0}.appsection{padding:10px 12px}.appsection .quicklinks{margin-bottom:0}"
    ".urow{display:grid;grid-template-columns:1fr auto;gap:10px;align-items:center;padding:9px 0;border-bottom:1px solid var(--eb-line-soft)}.urow:last-child{border-bottom:0}.urow small{display:block;color:var(--eb-muted);margin-top:2px}.urow form{display:inline}.uactions{display:grid;grid-template-columns:4em minmax(96px,max-content);gap:14px;align-items:center;justify-content:end;min-width:0}.uvalue{font-weight:700;white-space:nowrap}.uactions .uvalue{min-width:0;text-align:right;color:#344054}.uactions .btnlink,.uactions input[type=submit]{min-width:96px}.uactions form{display:block;margin:0}.uactions form input[type=submit]{width:100%;margin:0}.uactions.readonly{grid-template-columns:4em 96px}.pagination{display:grid;grid-template-columns:auto 1fr auto;gap:10px;align-items:center;border-top:1px solid var(--eb-line-soft);padding-top:7px;margin-top:7px;font-size:12px;font-weight:400}.pagerlinks,.pagerform{display:flex;flex-wrap:wrap;align-items:center;gap:4px}.pagerlinks{justify-content:center}.pagerform{justify-content:flex-end}.pagination .muted,.pagination label{display:inline-flex;align-items:center;min-height:26px;margin:0;font-weight:400;line-height:1}.pagination .btnlink,.pagination button,.pagination select,.pagination input{font-size:12px;min-height:26px;border-radius:6px;font-weight:400;line-height:1.1}.pagination .btnlink{padding:0 7px;background:var(--eb-button-soft);color:#526071}.pagination .btnlink.disabled{background:#f5f6f7;color:#9aa4b2}.pagination .current{background:var(--eb-primary-soft);color:var(--eb-primary);border:1px solid #c8dfe4}.pagination button{padding:0 8px;background:var(--eb-button-soft);color:#344054;border:1px solid var(--eb-button-border)}.pagination button:hover{background:var(--eb-button-soft-hover)}.pagination select,.pagination input{padding:2px 7px}.pagerform input[type=number]{width:6ch;margin:0}.pagerform select{width:auto;max-width:82px;margin:0}"
    ".tag{display:inline-flex;align-items:center;min-height:21px;padding:2px 7px;border-radius:999px;background:#eef2f4;color:#475467;font-size:11px;font-weight:750;white-space:nowrap}.tag.ok{background:var(--eb-ok-soft);color:var(--eb-ok)}.tag.warn{background:var(--eb-warn-soft);color:var(--eb-warn)}.tag.danger{background:var(--eb-danger-soft);color:var(--eb-danger)}.tag.info{background:var(--eb-info-soft);color:var(--eb-info)}.submetrics{display:grid;grid-template-columns:repeat(auto-fit,minmax(86px,1fr));gap:4px 12px;margin:0}.tag+.submetrics{margin-top:5px}.tag+.btnlink.compact{margin-left:6px;vertical-align:middle}.submetrics span{min-width:0}.submetrics b{display:block;color:var(--eb-muted);font-size:11px;font-weight:650;line-height:1.2}.submetrics em{display:block;font-style:normal;overflow-wrap:anywhere}.fsummary{border-collapse:collapse;width:100%;min-width:560px;font-size:13px}.fsummary th,.fsummary td{border-bottom:1px solid var(--eb-line);padding:7px 8px;text-align:left;vertical-align:top}.fsummary tr:last-child th,.fsummary tr:last-child td{border-bottom:0}.fsummary th{width:150px;color:var(--eb-muted);font-weight:650}.fsummary b{display:block;color:var(--eb-muted);font-size:11px;font-weight:650;line-height:1.2}.fsummary em{display:block;font-style:normal;overflow-wrap:anywhere}.fsummary .tag{margin-top:-1px}"
    ".btnlink,input.btnlink{display:inline-flex;align-items:center;justify-content:center;min-height:30px;padding:0 9px;border-radius:6px;background:var(--eb-button-soft);color:#344054;border:1px solid var(--eb-button-border);font-size:13px;font-weight:650;white-space:nowrap}.btnlink:hover,input.btnlink:hover{background:var(--eb-button-soft-hover)}.btnlink.info,input.btnlink.info{background:var(--eb-info-soft);color:var(--eb-info);border-color:#cbdde5}.btnlink.ok,input.btnlink.ok{background:var(--eb-ok-soft);color:var(--eb-ok);border-color:#bfe0d4}.btnlink.warn,input.btnlink.warn{background:var(--eb-warn-soft);color:var(--eb-warn);border-color:#efcf96}.btnlink.danger,input.btnlink.danger{background:var(--eb-danger-soft);color:var(--eb-danger);border-color:#efc0ba}.btnlink.secondary,input.btnlink.secondary{background:var(--eb-button-soft);color:#344054;border-color:var(--eb-button-border)}.btnlink.disabled{background:#eef2f4;color:#98a2b3;border-color:transparent}.btnlink.compact{min-height:26px;padding:0 8px;font-size:12px}.fsactions{display:flex;flex-wrap:wrap;gap:5px;align-items:center}.fsactions form{margin:0}.fsaction,.fsdelete{min-height:26px;padding:0 8px;border-radius:6px;font-size:12px}.part form{margin:0}"
    ".eb-inline-edit{display:none;border:1px solid #cbdde5;background:#f7fafb;border-radius:8px;padding:10px;margin:8px 0}.eb-inline-edit.open{display:block}.eb-inline-edit .actions{justify-content:flex-end}.eb-inline-error,.eb-dialog-error{display:none;color:var(--eb-danger);font-size:13px;margin:6px 0 0}.eb-inline-error.show,.eb-dialog-error.show{display:block}.eb-dialog-backdrop{position:fixed;inset:0;background:rgba(15,23,42,.28);display:none;align-items:center;justify-content:center;padding:18px;z-index:50}.eb-dialog-backdrop.open{display:flex}.eb-dialog{width:min(440px,100%);background:var(--eb-surface);border:1px solid var(--eb-line);border-radius:8px;box-shadow:0 18px 46px rgba(16,24,40,.18);padding:14px}.eb-dialog h2{font-size:16px;margin-bottom:8px}.eb-dialog .actions{justify-content:flex-end}.eb-dialog-close{float:right;background:var(--eb-button-soft);color:#344054;border:1px solid var(--eb-button-border);min-height:28px}.eb-busy{opacity:.7}"
    ".kv{border-collapse:collapse;width:100%;margin:0}.kv th,.kv td{border-bottom:1px solid var(--eb-line);padding:7px 5px;text-align:left;vertical-align:top}.kv tr:last-child th,.kv tr:last-child td{border-bottom:0}.kv th{width:30%;color:var(--eb-muted);font-weight:650}.statuspage{padding:10px 12px}.statuspage h2,.logpanel h2{margin-bottom:6px}.statuspage .kv{font-size:13px}.statuspage .kv th{width:176px;max-width:38%}"
    ".part{border-collapse:collapse;width:100%;min-width:640px;font-size:13px}.part th,.part td{border-bottom:1px solid var(--eb-line);padding:6px 5px;text-align:left;vertical-align:top}.part th{color:var(--eb-muted);font-weight:650}.part tr:last-child td{border-bottom:0}"
    ".tabs,.quicklinks{display:flex;flex-wrap:wrap;gap:6px;margin:8px 0 10px}.tabs a,.quicklinks a{font-size:13px;padding:5px 8px;margin:0;background:#f1f4f3;color:var(--eb-muted);border-radius:6px}.tabs a{display:inline-flex;align-items:center;gap:8px}.tabs a.active{background:var(--eb-primary-soft);color:var(--eb-primary);font-weight:700}.segsize{padding-left:7px;border-left:1px solid var(--eb-line);font-variant-numeric:tabular-nums}"
    ".logmeta{border-collapse:collapse;font-size:13px;line-height:1.45;margin:0}.logmeta th,.logmeta td{padding:3px 10px 3px 0;text-align:left;vertical-align:top}.logmeta th{width:112px;color:var(--eb-muted);font-weight:650}.logmeta td{color:var(--eb-ink)}.logpanel{padding:10px 12px}.logpanel .tabs{margin-bottom:8px}.statusline{min-height:1.45em}.toolsection{padding:12px;margin:12px 0;background:#fff;border:1px solid var(--eb-line);border-radius:8px}"
    "pre{white-space:pre;overflow-x:auto;word-break:normal;font-size:12px;line-height:1.45;background:#f1f4f3;border:1px solid var(--eb-line);border-radius:7px;padding:9px}.logframe{display:block;width:100%;height:62vh;min-height:320px;border:1px solid var(--eb-line);border-radius:7px;background:#f1f4f3}"
    "@media(max-width:760px){body{padding:10px}.metrics,.pagination,.urow,.statusgrid,.toolgrid,.toollinks,.hostfacts,.hostedit{grid-template-columns:1fr}.fieldgrid{grid-template-columns:1fr}.field.short,.field.med,.field.long,.field.full,.authpanel .field.med{grid-column:auto;max-width:none}.uactions,.uactions.readonly{grid-template-columns:minmax(0,max-content) minmax(88px,96px);justify-content:flex-start}.toollinks .urow{grid-template-columns:minmax(0,1fr) auto;gap:8px}.toollinks .uactions{grid-template-columns:72px;justify-content:end}.uactions .uvalue{text-align:left}.pagerlinks,.pagerform{justify-content:flex-start}.pagination .btnlink,.pagination button,.pagination select,.pagination input{min-height:32px}.heap{margin-left:0;text-align:left;white-space:normal}nav a{font-size:14px;padding:0 10px}.tag{white-space:normal}.eb-dialog-backdrop{align-items:flex-end;padding:10px}.eb-dialog{width:100%;max-height:92vh;overflow:auto}}";

const char WEB_HEAD[] PROGMEM =
    "<meta charset='UTF-8'><meta name='viewport' content='width=device-width,initial-scale=1'>"
    "<link rel='stylesheet' href='/esp32base/ui.css?v=" ESP32BASE_WEB_CSS_VERSION "'>"
    "<script>function once(f){if(f.dataset.busy)return false;f.dataset.busy=1;var b=f.querySelector('[type=submit]');if(b)b.disabled=true;return true;}function ebErr(box,msg){if(!box)return;box.textContent=msg||'Action failed';box.classList.add('show');}function ebOpenDialog(id){var d=document.getElementById(id);if(d){d.classList.add('open');var i=d.querySelector('input,select,button');if(i)i.focus();}}function ebCloseDialog(el){var d=el&&el.closest?el.closest('.eb-dialog-backdrop'):null;if(d)d.classList.remove('open');}function ebAjaxSubmit(f){if(!window.fetch)return true;if(f.dataset.busy)return false;f.dataset.busy=1;f.classList.add('eb-busy');var b=f.querySelector('[type=submit]'),e=f.querySelector('[data-eb-error]');if(b)b.disabled=true;if(e){e.textContent='';e.classList.remove('show');}fetch(f.action,{method:f.method||'POST',headers:{'X-Esp32Base-Ajax':'1','Accept':'application/json','Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams(new FormData(f)).toString(),credentials:'same-origin'}).then(function(r){return r.json().then(function(j){j.status=r.status;return j;});}).then(function(j){if(!j.ok){ebErr(e,j.error);return;}if(j.target&&j.html){var t=document.getElementById(j.target);if(t)t.outerHTML=j.html;}if(j.close)ebCloseDialog(f);}).catch(function(){ebErr(e,'Request failed.');}).finally(function(){delete f.dataset.busy;f.classList.remove('eb-busy');if(b)b.disabled=false;});return false;}document.addEventListener('submit',function(ev){var f=ev.target;if(f&&f.matches&&f.matches('form[data-eb-ajax]')){ev.preventDefault();ebAjaxSubmit(f);}});document.addEventListener('click',function(ev){var t=ev.target;if(t.matches('[data-eb-dialog-open]')){ev.preventDefault();ebOpenDialog(t.getAttribute('data-eb-dialog-open'));}if(t.matches('[data-eb-dialog-close]')){ev.preventDefault();ebCloseDialog(t);}if(t.matches('[data-eb-inline-toggle]')){ev.preventDefault();var e=document.getElementById(t.getAttribute('data-eb-inline-toggle'));if(e)e.classList.add('open');}if(t.matches('[data-eb-inline-close]')){ev.preventDefault();var c=document.getElementById(t.getAttribute('data-eb-inline-close'));if(c)c.classList.remove('open');}});document.addEventListener('keydown',function(ev){if(ev.key=='Escape'){document.querySelectorAll('.eb-dialog-backdrop.open').forEach(function(d){d.classList.remove('open');});}});</script>";

#if ESP32BASE_ENABLE_APP_CONFIG
// Page-scoped CSS for /esp32base/app-config. Kept out of WEB_HEAD so Status, Logs, WiFi,
// Auth, OTA and Tools pages don't pay ~700 B per request for App Config-only styles.
const char WEB_APPCFG_STYLE[] PROGMEM =
    "<style>"
    ".appcfg{margin:0}.appcfg .pagehead,.appcfg .panel{margin:12px 0}.appcfg .panel{padding:12px}.appcfg .acfield{max-width:760px;margin:0 0 11px}.appcfg .acfield:last-child{margin-bottom:0}.appcfg .acfield>label{margin:0 0 3px}.appcfg input:not([type]),.appcfg input[type=text],.appcfg input[type=number],.appcfg select{font-size:14px;padding:6px 8px;margin:0;border:1px solid #ccd5dd;border-radius:7px;box-sizing:border-box;background:#fff;color:#1f2933}.appcfg input:not([type]),.appcfg input[type=text],.appcfg input[type=number]{width:100%}.appcfg select{max-width:260px;width:auto}.appcfg .acrow{display:flex;gap:7px;align-items:center;max-width:760px}.appcfg .acrow input{flex:1 1 auto;min-width:0}.appcfg .acrow input[type=number]{flex:0 1 14ch;width:14ch}.appcfg .unit{color:var(--eb-muted);font-size:13px;flex:0 0 auto}.appcfg .help{color:var(--eb-muted);font-size:13px;margin:4px 0 0}.appcfg .restart{margin-left:4px;font-size:11px;vertical-align:1px}.appcfg .confirmbox{display:none;border:1px solid var(--eb-line);background:var(--eb-surface);border-radius:8px;padding:10px 12px;margin:12px 0;overflow-x:auto}.appcfg .confirmbox h2{margin-bottom:4px}.appcfg .confirmbox .reviewhint{color:var(--eb-muted);font-size:13px;margin:0 0 8px}.appcfg .confirmbox table,.appcfg .pendingbox table{border-collapse:collapse;width:100%;font-size:13px}.appcfg .confirmbox th,.appcfg .confirmbox td,.appcfg .pendingbox th,.appcfg .pendingbox td{border-bottom:1px solid var(--eb-line);padding:5px;text-align:left;vertical-align:top}.appcfg .confirmbox tr:last-child td,.appcfg .pendingbox tr:last-child td{border-bottom:0}.appcfg .acgroup th{background:var(--eb-soft);color:var(--eb-muted);font-size:12px;font-weight:700}.appcfg .confirmbox .cancelbtn{background:#f3f5f5;color:#344054;border:1px solid var(--eb-line)}.appcfg .confirmbox .cancelbtn:hover{background:#e9eef2}.appcfg .pendingbox{border-color:#efcf96;background:var(--eb-warn-soft);overflow-x:auto}.appcfg #acsavebar,.appcfg .confirmbox .actions{max-width:760px}@media(max-width:640px){.appcfg select{width:100%;max-width:none}.appcfg .acrow{align-items:flex-start}.appcfg .acrow input[type=number]{max-width:100%}.appcfg .unit{padding-top:7px}}"
    "</style>";
#endif

void handleUiCss() {
    markRequest();
    g_server.sendHeader("Cache-Control", "public, max-age=86400");
    g_server.sendHeader("X-Content-Type-Options", "nosniff");
    g_server.send_P(200, WEB_CSS_TYPE, WEB_CSS);
}

} // namespace esp32base_web

#endif
