[platformio]
default_envs = esp32dev

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
lib_extra_dirs = ../..
lib_ldf_mode = deep+
build_flags =
    -DESP32BASE_LOG_LEVEL=0

[env:esp32dev]
board = esp32dev
board_build.partitions = ../../partitions/esp32-4mb-ota-balanced.csv

[env:esp32-s3-devkitc-1]
board = esp32-s3-devkitc-1
board_build.partitions = ../../partitions/esp32-s3-8mb-ota-balanced.csv

[env:esp32-c3-devkitm-1]
board = esp32-c3-devkitm-1
board_build.partitions = ../../partitions/esp32-c3-4mb-ota-balanced.csv
