[platformio]
default_envs = esp32_net_runtime

[env:esp32_net_runtime]
platform = platformio/espressif32@6.7.0
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_extra_dirs = ../..
board_build.partitions = ../../partitions/esp32-4mb-ota-balanced.csv
lib_deps =
  WiFi
  DNSServer
  ESPmDNS
  LittleFS
build_flags =
  -D ESP32BASE_PROFILE=ESP32BASE_PROFILE_NET_RUNTIME
  -I ${platformio.packages_dir}/framework-arduinoespressif32/libraries/FS/src
  -I ${platformio.packages_dir}/framework-arduinoespressif32/libraries/Hash/src
  -I ${platformio.packages_dir}/framework-arduinoespressif32/libraries/DNSServer/src
  -I ${platformio.packages_dir}/framework-arduinoespressif32/libraries/ESPmDNS/src
  -I ${platformio.packages_dir}/framework-arduinoespressif32/libraries/LittleFS/src
  -I ${platformio.packages_dir}/framework-arduinoespressif32/libraries/WiFi/src

[env:esp32s3_net_runtime]
extends = env:esp32_net_runtime
board = esp32-s3-devkitc-1
board_build.partitions = ../../partitions/esp32-s3-8mb-ota-balanced.csv
