#!/usr/bin/env python3
"""Generate deterministic, profile-specific gzip CSS; no runtime compression or raw copy."""
import argparse
import ast
import gzip
import hashlib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'src/web/internal/WebCssSource.inc'
TARGET = ROOT / 'src/web/internal/WebCssGzip.inc'
FLAGS = ('ESP32BASE_ENABLE_FS', 'ESP32BASE_ENABLE_OTA', 'ESP32BASE_ENABLE_FILELOG')

def source_bytes(values):
    active = True
    parts = []
    for line in SOURCE.read_text().splitlines():
        line = line.strip()
        if line.startswith('#if '):
            active = any(values[name.strip()] for name in line[4:].split('||'))
        elif line == '#endif':
            active = True
        elif active and line.startswith('"'):
            parts.append(ast.literal_eval(line))
    return ''.join(parts).encode()

def generated():
    output = ['// Generated by scripts/generate_web_css.py. Do not edit.']
    for mask in range(8):
        values = {flag: (mask >> index) & 1 for index, flag in enumerate(FLAGS)}
        raw = source_bytes(values)
        data = bytearray(gzip.compress(raw, compresslevel=9, mtime=0))
        data[9] = 255  # Fixed gzip OS marker across Python/platform versions.
        assert gzip.decompress(data) == raw
        condition = ' && '.join(('' if values[flag] else '!') + flag for flag in FLAGS)
        output += [('#if ' if mask == 0 else '#elif ') + condition,
                   f'// CSS {len(raw)} B -> gzip {len(data)} B.',
                   '#ifndef ESP32BASE_WEB_CSS_VERSION',
                   '#define ESP32BASE_WEB_CSS_VERSION "' + hashlib.sha256(raw).hexdigest()[:12] + '"',
                   '#endif',
                   'const uint8_t WEB_CSS_GZIP[] PROGMEM = {']
        output += ['    ' + ', '.join(f'0x{byte:02x}' for byte in data[i:i+16]) + ',' for i in range(0, len(data), 16)]
        output += ['};']
    return '\n'.join(output + ['#endif', ''])

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    result = generated()
    if args.check:
        if not TARGET.exists() or TARGET.read_text() != result:
            raise SystemExit('CSS gzip is stale: run python3 scripts/generate_web_css.py')
        print('CSS gzip matches all 8 feature combinations; lossless round-trip passed')
    else:
        TARGET.write_text(result)

if __name__ == '__main__':
    main()
