#!/usr/bin/env python3
"""Lossless, deterministic gzip for common script and page-scoped config CSS."""
import argparse
import gzip
import hashlib
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
TARGET = ROOT / 'src/web/internal/WebPageAssetsGzip.inc'
ASSETS = (('SCRIPT', 'WebCommonScript.js', None),
          ('APPCFG', 'WebAppConfigStyle.css', 'ESP32BASE_ENABLE_APP_CONFIG'),
          ('APPCFG_SCRIPT', 'WebAppConfigScript.js', 'ESP32BASE_ENABLE_APP_CONFIG'),
          ('OTA_SCRIPT', 'WebOtaScript.js', 'ESP32BASE_ENABLE_OTA'),
          ('FS_SCRIPT', 'WebFsScript.js', 'ESP32BASE_ENABLE_FS'))

def generated():
    lines = ['// Generated by scripts/generate_web_page_assets.py. Do not edit.']
    for name, filename, guard in ASSETS:
        raw = (ROOT / 'src/web/internal' / filename).read_bytes()
        data = bytearray(gzip.compress(raw, compresslevel=9, mtime=0))
        data[9] = 255
        assert gzip.decompress(data) == raw
        if guard:
            lines.append('#if ' + guard)
        lines += [f'// {filename}: {len(raw)} B -> {len(data)} B.',
                  f'#define WEB_{name}_ASSET_VERSION "{hashlib.sha256(raw).hexdigest()[:12]}"',
                  f'const uint8_t WEB_{name}_GZIP[] PROGMEM = {{']
        lines += ['    ' + ', '.join(f'0x{b:02x}' for b in data[i:i+16]) + ',' for i in range(0,len(data),16)]
        lines.append('};')
        if guard:
            lines.append('#endif')
    return '\n'.join(lines) + '\n'

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    if args.check:
        assert TARGET.read_text() == generated(), 'Page assets stale; run scripts/generate_web_page_assets.py'
        print('Common script/config CSS gzip: lossless generation check passed')
    else:
        TARGET.write_text(generated())
