#pragma once

#ifndef ESP32BASE_ENABLE_BUS
#define ESP32BASE_ENABLE_BUS 0
#endif
#ifndef ESP32BASE_ENABLE_WATCHDOG
#define ESP32BASE_ENABLE_WATCHDOG 0
#endif
#ifndef ESP32BASE_ENABLE_SLEEP
#define ESP32BASE_ENABLE_SLEEP 0
#endif
#ifndef ESP32BASE_ENABLE_FS
#define ESP32BASE_ENABLE_FS 0
#endif
#ifndef ESP32BASE_ENABLE_FILELOG
#if ESP32BASE_ENABLE_FS
#define ESP32BASE_ENABLE_FILELOG 1
#else
#define ESP32BASE_ENABLE_FILELOG 0
#endif
#endif
#ifndef ESP32BASE_ENABLE_RS485_PORT
#define ESP32BASE_ENABLE_RS485_PORT 0
#endif
#ifndef ESP32BASE_ENABLE_APP_EVENTS
#define ESP32BASE_ENABLE_APP_EVENTS 0
#endif
#ifndef ESP32BASE_ENABLE_APP_EVENT_CONDITIONS
#define ESP32BASE_ENABLE_APP_EVENT_CONDITIONS ESP32BASE_ENABLE_APP_EVENTS
#endif
#ifndef ESP32BASE_ENABLE_RECORD_STORE
#if ESP32BASE_ENABLE_APP_EVENTS
#define ESP32BASE_ENABLE_RECORD_STORE 1
#else
#define ESP32BASE_ENABLE_RECORD_STORE 0
#endif
#endif
#ifndef ESP32BASE_APP_EVENT_STORE_MAX_BYTES
#define ESP32BASE_APP_EVENT_STORE_MAX_BYTES (100UL * 1024UL)
#endif
#ifndef ESP32BASE_ENABLE_HEALTH
#define ESP32BASE_ENABLE_HEALTH 0
#endif
#ifndef ESP32BASE_ENABLE_WIFI
#define ESP32BASE_ENABLE_WIFI 0
#endif
#ifndef ESP32BASE_ENABLE_MQTT
#define ESP32BASE_ENABLE_MQTT 0
#endif
#ifndef ESP32BASE_MQTT_ALLOW_PLAINTEXT
#define ESP32BASE_MQTT_ALLOW_PLAINTEXT 0
#endif
#ifndef ESP32BASE_MQTT_ALLOW_UNCHECKED_CERTIFICATE_DATES
#define ESP32BASE_MQTT_ALLOW_UNCHECKED_CERTIFICATE_DATES 0
#endif
#ifndef ESP32BASE_MQTT_MAX_TOPIC_BYTES
#define ESP32BASE_MQTT_MAX_TOPIC_BYTES 128
#endif
#ifndef ESP32BASE_MQTT_MAX_PAYLOAD_BYTES
#define ESP32BASE_MQTT_MAX_PAYLOAD_BYTES 512
#endif
#ifndef ESP32BASE_MQTT_MAX_SUBSCRIPTIONS
#define ESP32BASE_MQTT_MAX_SUBSCRIPTIONS 8
#endif
#ifndef ESP32BASE_MQTT_INCOMING_SLOTS
#define ESP32BASE_MQTT_INCOMING_SLOTS 2
#endif
#ifndef ESP32BASE_MQTT_EVENT_SLOTS
#define ESP32BASE_MQTT_EVENT_SLOTS 16
#endif
#ifndef ESP32BASE_MQTT_MAX_INFLIGHT_QOS1
#define ESP32BASE_MQTT_MAX_INFLIGHT_QOS1 4
#endif
#ifndef ESP32BASE_MQTT_MAX_OUTBOX_BYTES
#define ESP32BASE_MQTT_MAX_OUTBOX_BYTES 4096
#endif
#ifndef ESP32BASE_MQTT_TASK_STACK_BYTES
#define ESP32BASE_MQTT_TASK_STACK_BYTES 6144
#endif
#ifndef ESP32BASE_MQTT_MAX_CA_CERT_BYTES
#define ESP32BASE_MQTT_MAX_CA_CERT_BYTES 6144
#endif
#ifndef ESP32BASE_MQTT_MAX_IDENTITY_PEM_BYTES
#define ESP32BASE_MQTT_MAX_IDENTITY_PEM_BYTES 4096
#endif
#ifndef ESP32BASE_ENABLE_WIFI_RECOVERY_BUTTON
#define ESP32BASE_ENABLE_WIFI_RECOVERY_BUTTON ESP32BASE_ENABLE_WIFI
#endif
#ifndef ESP32BASE_WIFI_RECOVERY_BUTTON_DEFAULT_ENABLED
#define ESP32BASE_WIFI_RECOVERY_BUTTON_DEFAULT_ENABLED 1
#endif
#ifndef ESP32BASE_WIFI_RECOVERY_BUTTON_GPIO
#if defined(CONFIG_IDF_TARGET_ESP32C3)
#define ESP32BASE_WIFI_RECOVERY_BUTTON_GPIO 9
#else
#define ESP32BASE_WIFI_RECOVERY_BUTTON_GPIO 0
#endif
#endif
#ifndef ESP32BASE_WIFI_RECOVERY_BUTTON_HOLD_MS
#define ESP32BASE_WIFI_RECOVERY_BUTTON_HOLD_MS 10000UL
#endif
#ifndef ESP32BASE_ENABLE_DNS
#define ESP32BASE_ENABLE_DNS 0
#endif
#ifndef ESP32BASE_ENABLE_NTP
#define ESP32BASE_ENABLE_NTP 0
#endif
#ifndef ESP32BASE_NTP_GMT_OFFSET_SEC
#define ESP32BASE_NTP_GMT_OFFSET_SEC (8L * 3600L)
#endif
#ifndef ESP32BASE_NTP_DAYLIGHT_OFFSET_SEC
#define ESP32BASE_NTP_DAYLIGHT_OFFSET_SEC 0L
#endif
#ifndef ESP32BASE_NTP_SYNC_MIN_EPOCH
#define ESP32BASE_NTP_SYNC_MIN_EPOCH 1700000000UL
#endif
#ifndef ESP32BASE_ENABLE_RTC
#define ESP32BASE_ENABLE_RTC 0
#endif
#define ESP32BASE_RTC_DRIVER_DS3231 1
#define ESP32BASE_RTC_DRIVER_PCF8563 2
#ifndef ESP32BASE_RTC_DRIVER
#define ESP32BASE_RTC_DRIVER ESP32BASE_RTC_DRIVER_DS3231
#endif
#ifndef ESP32BASE_RTC_I2C_ADDR
#define ESP32BASE_RTC_I2C_ADDR 0
#endif
#ifndef ESP32BASE_RTC_AUTO_WIRE_BEGIN
#define ESP32BASE_RTC_AUTO_WIRE_BEGIN 0
#endif
#ifndef ESP32BASE_RTC_SDA
#define ESP32BASE_RTC_SDA -1
#endif
#ifndef ESP32BASE_RTC_SCL
#define ESP32BASE_RTC_SCL -1
#endif
#ifndef ESP32BASE_RTC_I2C_CLOCK_HZ
#define ESP32BASE_RTC_I2C_CLOCK_HZ 100000
#endif
#ifndef ESP32BASE_RTC_NTP_WRITEBACK
#define ESP32BASE_RTC_NTP_WRITEBACK 1
#endif
#ifndef ESP32BASE_RTC_WRITEBACK_THRESHOLD_SEC
#define ESP32BASE_RTC_WRITEBACK_THRESHOLD_SEC 2
#endif
#ifndef ESP32BASE_RTC_STATUS_REFRESH_MS
#define ESP32BASE_RTC_STATUS_REFRESH_MS 0
#endif
#ifndef ESP32BASE_TIME_SYNC_MIN_EPOCH
#ifdef ESP32BASE_NTP_SYNC_MIN_EPOCH
#define ESP32BASE_TIME_SYNC_MIN_EPOCH ESP32BASE_NTP_SYNC_MIN_EPOCH
#else
#define ESP32BASE_TIME_SYNC_MIN_EPOCH 1700000000UL
#endif
#endif
#ifndef ESP32BASE_ENABLE_TIME
#if ESP32BASE_ENABLE_NTP || ESP32BASE_ENABLE_RTC || ESP32BASE_ENABLE_RECORD_STORE || ESP32BASE_ENABLE_APP_EVENTS || ESP32BASE_ENABLE_WEB || ESP32BASE_ENABLE_MQTT
#define ESP32BASE_ENABLE_TIME 1
#else
#define ESP32BASE_ENABLE_TIME 0
#endif
#endif
#ifndef ESP32BASE_ENABLE_MDNS
#define ESP32BASE_ENABLE_MDNS 0
#endif
#ifndef ESP32BASE_ENABLE_WEB
#define ESP32BASE_ENABLE_WEB 0
#endif
#ifndef ESP32BASE_ENABLE_APP_CONFIG
#define ESP32BASE_ENABLE_APP_CONFIG 0
#endif
#ifndef ESP32BASE_ENABLE_OTA
#define ESP32BASE_ENABLE_OTA 0
#endif
#ifndef ESP32BASE_WEB_ALLOW_INSECURE_DEFAULT_AUTH
#define ESP32BASE_WEB_ALLOW_INSECURE_DEFAULT_AUTH 0
#endif

#if ESP32BASE_ENABLE_WEB && !ESP32BASE_ENABLE_WIFI
#error "ESP32BASE_ENABLE_WEB requires ESP32BASE_ENABLE_WIFI"
#endif
#if ESP32BASE_ENABLE_WIFI_RECOVERY_BUTTON && !ESP32BASE_ENABLE_WIFI
#error "ESP32BASE_ENABLE_WIFI_RECOVERY_BUTTON requires ESP32BASE_ENABLE_WIFI"
#endif
#if ESP32BASE_ENABLE_MQTT && !ESP32BASE_ENABLE_WIFI
#error "ESP32BASE_ENABLE_MQTT requires ESP32BASE_ENABLE_WIFI"
#endif
#if ESP32BASE_ENABLE_MQTT && !ESP32BASE_ENABLE_TIME
#error "ESP32BASE_ENABLE_MQTT requires ESP32BASE_ENABLE_TIME"
#endif
#if ESP32BASE_ENABLE_MQTT != 0 && ESP32BASE_ENABLE_MQTT != 1
#error "ESP32BASE_ENABLE_MQTT must be 0 or 1"
#endif
#if ESP32BASE_MQTT_ALLOW_PLAINTEXT != 0 && ESP32BASE_MQTT_ALLOW_PLAINTEXT != 1
#error "ESP32BASE_MQTT_ALLOW_PLAINTEXT must be 0 or 1"
#endif
#if ESP32BASE_MQTT_ALLOW_UNCHECKED_CERTIFICATE_DATES != 0 && ESP32BASE_MQTT_ALLOW_UNCHECKED_CERTIFICATE_DATES != 1
#error "ESP32BASE_MQTT_ALLOW_UNCHECKED_CERTIFICATE_DATES must be 0 or 1"
#endif
#if ESP32BASE_MQTT_MAX_TOPIC_BYTES < 32 || ESP32BASE_MQTT_MAX_TOPIC_BYTES > 256
#error "ESP32BASE_MQTT_MAX_TOPIC_BYTES must be 32..256"
#endif
#if ESP32BASE_MQTT_MAX_PAYLOAD_BYTES < 64 || ESP32BASE_MQTT_MAX_PAYLOAD_BYTES > 2048
#error "ESP32BASE_MQTT_MAX_PAYLOAD_BYTES must be 64..2048"
#endif
#if ESP32BASE_MQTT_MAX_SUBSCRIPTIONS < 1 || ESP32BASE_MQTT_MAX_SUBSCRIPTIONS > 16
#error "ESP32BASE_MQTT_MAX_SUBSCRIPTIONS must be 1..16"
#endif
#if ESP32BASE_MQTT_INCOMING_SLOTS < 1 || ESP32BASE_MQTT_INCOMING_SLOTS > 4
#error "ESP32BASE_MQTT_INCOMING_SLOTS must be 1..4"
#endif
#if ESP32BASE_MQTT_EVENT_SLOTS < 4 || ESP32BASE_MQTT_EVENT_SLOTS > 16
#error "ESP32BASE_MQTT_EVENT_SLOTS must be 4..16"
#endif
#if ESP32BASE_MQTT_MAX_INFLIGHT_QOS1 < 1 || ESP32BASE_MQTT_MAX_INFLIGHT_QOS1 > 8
#error "ESP32BASE_MQTT_MAX_INFLIGHT_QOS1 must be 1..8"
#endif
#if ESP32BASE_MQTT_MAX_OUTBOX_BYTES < 1024 || ESP32BASE_MQTT_MAX_OUTBOX_BYTES > 16384
#error "ESP32BASE_MQTT_MAX_OUTBOX_BYTES must be 1024..16384"
#endif
#if ESP32BASE_MQTT_TASK_STACK_BYTES < 4096 || ESP32BASE_MQTT_TASK_STACK_BYTES > 8192
#error "ESP32BASE_MQTT_TASK_STACK_BYTES must be 4096..8192"
#endif
#if ESP32BASE_MQTT_MAX_CA_CERT_BYTES < 1024 || ESP32BASE_MQTT_MAX_CA_CERT_BYTES > 16384
#error "ESP32BASE_MQTT_MAX_CA_CERT_BYTES must be 1024..16384"
#endif
#if ESP32BASE_MQTT_MAX_IDENTITY_PEM_BYTES < 1024 || ESP32BASE_MQTT_MAX_IDENTITY_PEM_BYTES > 8192
#error "ESP32BASE_MQTT_MAX_IDENTITY_PEM_BYTES must be 1024..8192"
#endif
#if ESP32BASE_ENABLE_WIFI_RECOVERY_BUTTON != 0 && ESP32BASE_ENABLE_WIFI_RECOVERY_BUTTON != 1
#error "ESP32BASE_ENABLE_WIFI_RECOVERY_BUTTON must be 0 or 1"
#endif
#if ESP32BASE_WIFI_RECOVERY_BUTTON_DEFAULT_ENABLED != 0 && ESP32BASE_WIFI_RECOVERY_BUTTON_DEFAULT_ENABLED != 1
#error "ESP32BASE_WIFI_RECOVERY_BUTTON_DEFAULT_ENABLED must be 0 or 1"
#endif
#if ESP32BASE_WIFI_RECOVERY_BUTTON_HOLD_MS < 1000UL || ESP32BASE_WIFI_RECOVERY_BUTTON_HOLD_MS > 60000UL
#error "ESP32BASE_WIFI_RECOVERY_BUTTON_HOLD_MS must be 1000..60000"
#endif
#if ESP32BASE_ENABLE_APP_CONFIG && !ESP32BASE_ENABLE_WEB
#error "ESP32BASE_ENABLE_APP_CONFIG requires ESP32BASE_ENABLE_WEB"
#endif
#if ESP32BASE_ENABLE_APP_CONFIG
  #ifndef ESP32BASE_APP_CONFIG_MAX_GROUPS
  #error "ESP32BASE_APP_CONFIG_MAX_GROUPS must be defined when ESP32BASE_ENABLE_APP_CONFIG=1"
  #endif
  #ifndef ESP32BASE_APP_CONFIG_MAX_FIELDS
  #error "ESP32BASE_APP_CONFIG_MAX_FIELDS must be defined when ESP32BASE_ENABLE_APP_CONFIG=1"
  #endif
  #if ESP32BASE_APP_CONFIG_MAX_GROUPS < 1 || ESP32BASE_APP_CONFIG_MAX_GROUPS > 16
  #error "ESP32BASE_APP_CONFIG_MAX_GROUPS must be 1..16"
  #endif
  #if ESP32BASE_APP_CONFIG_MAX_FIELDS < 1 || ESP32BASE_APP_CONFIG_MAX_FIELDS > 128
  #error "ESP32BASE_APP_CONFIG_MAX_FIELDS must be 1..128"
  #endif
#endif
#if ESP32BASE_ENABLE_OTA && (!ESP32BASE_ENABLE_WIFI || !ESP32BASE_ENABLE_WEB)
#error "ESP32BASE_ENABLE_OTA requires ESP32BASE_ENABLE_WIFI and ESP32BASE_ENABLE_WEB"
#endif
#if ESP32BASE_ENABLE_FILELOG && !ESP32BASE_ENABLE_FS
#error "ESP32BASE_ENABLE_FILELOG requires ESP32BASE_ENABLE_FS"
#endif
#if ESP32BASE_ENABLE_APP_EVENTS && !ESP32BASE_ENABLE_FS
#error "ESP32BASE_ENABLE_APP_EVENTS requires ESP32BASE_ENABLE_FS"
#endif
#if ESP32BASE_ENABLE_RECORD_STORE && !ESP32BASE_ENABLE_FS
#error "ESP32BASE_ENABLE_RECORD_STORE requires ESP32BASE_ENABLE_FS"
#endif
#if ESP32BASE_ENABLE_RECORD_STORE && !ESP32BASE_ENABLE_TIME
#error "ESP32BASE_ENABLE_RECORD_STORE requires ESP32BASE_ENABLE_TIME"
#endif
#if ESP32BASE_ENABLE_APP_EVENTS && !ESP32BASE_ENABLE_RECORD_STORE
#error "ESP32BASE_ENABLE_APP_EVENTS requires ESP32BASE_ENABLE_RECORD_STORE"
#endif
#if ESP32BASE_ENABLE_APP_EVENT_CONDITIONS && !ESP32BASE_ENABLE_APP_EVENTS
#error "ESP32BASE_ENABLE_APP_EVENT_CONDITIONS requires ESP32BASE_ENABLE_APP_EVENTS"
#endif
#if ESP32BASE_ENABLE_APP_EVENT_CONDITIONS != 0 && ESP32BASE_ENABLE_APP_EVENT_CONDITIONS != 1
#error "ESP32BASE_ENABLE_APP_EVENT_CONDITIONS must be 0 or 1"
#endif
#if ESP32BASE_ENABLE_APP_EVENTS && ESP32BASE_APP_EVENT_STORE_MAX_BYTES < 208UL
#error "ESP32BASE_APP_EVENT_STORE_MAX_BYTES is too small"
#endif
#if ESP32BASE_ENABLE_DNS && !ESP32BASE_ENABLE_WIFI
#error "ESP32BASE_ENABLE_DNS requires ESP32BASE_ENABLE_WIFI"
#endif
#if ESP32BASE_ENABLE_NTP && !ESP32BASE_ENABLE_WIFI
#error "ESP32BASE_ENABLE_NTP requires ESP32BASE_ENABLE_WIFI"
#endif
#if ESP32BASE_ENABLE_RTC && !ESP32BASE_ENABLE_TIME
#error "ESP32BASE_ENABLE_RTC requires ESP32BASE_ENABLE_TIME"
#endif
#if ESP32BASE_ENABLE_RTC && \
    ESP32BASE_RTC_DRIVER != ESP32BASE_RTC_DRIVER_DS3231 && \
    ESP32BASE_RTC_DRIVER != ESP32BASE_RTC_DRIVER_PCF8563
#error "ESP32BASE_RTC_DRIVER must be ESP32BASE_RTC_DRIVER_DS3231 or ESP32BASE_RTC_DRIVER_PCF8563"
#endif
#if ESP32BASE_RTC_AUTO_WIRE_BEGIN != 0 && ESP32BASE_RTC_AUTO_WIRE_BEGIN != 1
#error "ESP32BASE_RTC_AUTO_WIRE_BEGIN must be 0 or 1"
#endif
#if ESP32BASE_RTC_I2C_ADDR < 0 || ESP32BASE_RTC_I2C_ADDR > 0x7F
#error "ESP32BASE_RTC_I2C_ADDR must be 0 or a 7-bit I2C address"
#endif
#if ESP32BASE_RTC_AUTO_WIRE_BEGIN && ((ESP32BASE_RTC_SDA < 0) != (ESP32BASE_RTC_SCL < 0))
#error "ESP32BASE_RTC_SDA and ESP32BASE_RTC_SCL must be configured together"
#endif
#if ESP32BASE_RTC_I2C_CLOCK_HZ <= 0
#error "ESP32BASE_RTC_I2C_CLOCK_HZ must be > 0"
#endif
#if ESP32BASE_RTC_NTP_WRITEBACK != 0 && ESP32BASE_RTC_NTP_WRITEBACK != 1
#error "ESP32BASE_RTC_NTP_WRITEBACK must be 0 or 1"
#endif
#if ESP32BASE_RTC_WRITEBACK_THRESHOLD_SEC < 0
#error "ESP32BASE_RTC_WRITEBACK_THRESHOLD_SEC must be >= 0"
#endif
#if ESP32BASE_RTC_STATUS_REFRESH_MS < 0
#error "ESP32BASE_RTC_STATUS_REFRESH_MS must be >= 0"
#endif
#if ESP32BASE_ENABLE_NTP && !ESP32BASE_ENABLE_TIME
#error "ESP32BASE_ENABLE_NTP requires ESP32BASE_ENABLE_TIME"
#endif
#if ESP32BASE_ENABLE_MDNS && !ESP32BASE_ENABLE_WIFI
#error "ESP32BASE_ENABLE_MDNS requires ESP32BASE_ENABLE_WIFI"
#endif
