#pragma once

#if defined(ESP32BASE_PROFILE_CORE) || defined(ESP32BASE_PROFILE_RUNTIME) || \
    defined(ESP32BASE_PROFILE_NET) || defined(ESP32BASE_PROFILE_NET_RUNTIME) || \
    defined(ESP32BASE_PROFILE_WEB) || defined(ESP32BASE_PROFILE_WEB_RUNTIME) || \
    defined(ESP32BASE_PROFILE_FULL)
#error "Legacy Esp32Base Profile macros were removed; select MINIMAL, OFFLINE, LOCAL, or IOT"
#endif
#if defined(ESP32BASE_ENABLE_WEB_OTA) || defined(ESP32BASE_ENABLE_ARDUINO_OTA)
#error "Legacy OTA macros were removed; ESP32BASE_ENABLE_OTA controls HTTP Web OTA"
#endif

#define ESP32BASE_PROFILE_MINIMAL 1
#define ESP32BASE_PROFILE_OFFLINE 2
#define ESP32BASE_PROFILE_LOCAL 3
#define ESP32BASE_PROFILE_IOT 4

#ifndef ESP32BASE_PROFILE
#define ESP32BASE_PROFILE ESP32BASE_PROFILE_MINIMAL
#endif

#if ESP32BASE_PROFILE != ESP32BASE_PROFILE_MINIMAL && \
    ESP32BASE_PROFILE != ESP32BASE_PROFILE_OFFLINE && \
    ESP32BASE_PROFILE != ESP32BASE_PROFILE_LOCAL && \
    ESP32BASE_PROFILE != ESP32BASE_PROFILE_IOT
#error "ESP32BASE_PROFILE must be one of ESP32BASE_PROFILE_MINIMAL, ESP32BASE_PROFILE_OFFLINE, ESP32BASE_PROFILE_LOCAL, or ESP32BASE_PROFILE_IOT"
#endif

#ifndef ESP32BASE_ENABLE_LOG
#define ESP32BASE_ENABLE_LOG 1
#endif
#ifndef ESP32BASE_ENABLE_CONFIG
#define ESP32BASE_ENABLE_CONFIG 1
#endif
#ifndef ESP32BASE_ENABLE_SYSTEM
#define ESP32BASE_ENABLE_SYSTEM 1
#endif

#if ESP32BASE_ENABLE_LOG != 1 || ESP32BASE_ENABLE_CONFIG != 1 || ESP32BASE_ENABLE_SYSTEM != 1
#error "Log, Config, and System are mandatory Esp32Base core capabilities and must remain enabled"
#endif

#if ESP32BASE_PROFILE == ESP32BASE_PROFILE_OFFLINE || \
    ESP32BASE_PROFILE == ESP32BASE_PROFILE_LOCAL || \
    ESP32BASE_PROFILE == ESP32BASE_PROFILE_IOT
  #ifndef ESP32BASE_ENABLE_WATCHDOG
  #define ESP32BASE_ENABLE_WATCHDOG 1
  #endif
  #ifndef ESP32BASE_ENABLE_FS
  #define ESP32BASE_ENABLE_FS 1
  #endif
  #ifndef ESP32BASE_ENABLE_HEALTH
  #define ESP32BASE_ENABLE_HEALTH 1
  #endif
#endif

#if ESP32BASE_PROFILE == ESP32BASE_PROFILE_LOCAL || \
    ESP32BASE_PROFILE == ESP32BASE_PROFILE_IOT
  #ifndef ESP32BASE_ENABLE_WIFI
  #define ESP32BASE_ENABLE_WIFI 1
  #endif
  #ifndef ESP32BASE_ENABLE_DNS
  #define ESP32BASE_ENABLE_DNS 1
  #endif
  #ifndef ESP32BASE_ENABLE_NTP
  #define ESP32BASE_ENABLE_NTP 1
  #endif
  #ifndef ESP32BASE_ENABLE_MDNS
  #define ESP32BASE_ENABLE_MDNS 1
  #endif
  #ifndef ESP32BASE_ENABLE_WEB
  #define ESP32BASE_ENABLE_WEB 1
  #endif
  #ifndef ESP32BASE_ENABLE_OTA
  #define ESP32BASE_ENABLE_OTA 1
  #endif
#endif

#if ESP32BASE_PROFILE == ESP32BASE_PROFILE_IOT
  #ifndef ESP32BASE_ENABLE_MQTT
  #define ESP32BASE_ENABLE_MQTT 1
  #endif
#endif

#include "Esp32BaseCapabilityConfig.h"
