#pragma once

#define ESP32BASE_PROFILE_CORE 1
#define ESP32BASE_PROFILE_RUNTIME 2
#define ESP32BASE_PROFILE_NET 3
#define ESP32BASE_PROFILE_NET_RUNTIME 4
#define ESP32BASE_PROFILE_WEB 5
#define ESP32BASE_PROFILE_WEB_RUNTIME 6
#define ESP32BASE_PROFILE_FULL 7

#ifndef ESP32BASE_PROFILE
#define ESP32BASE_PROFILE ESP32BASE_PROFILE_CORE
#endif

#if ESP32BASE_PROFILE != ESP32BASE_PROFILE_CORE && \
    ESP32BASE_PROFILE != ESP32BASE_PROFILE_RUNTIME && \
    ESP32BASE_PROFILE != ESP32BASE_PROFILE_NET && \
    ESP32BASE_PROFILE != ESP32BASE_PROFILE_NET_RUNTIME && \
    ESP32BASE_PROFILE != ESP32BASE_PROFILE_WEB && \
    ESP32BASE_PROFILE != ESP32BASE_PROFILE_WEB_RUNTIME && \
    ESP32BASE_PROFILE != ESP32BASE_PROFILE_FULL
#error "ESP32BASE_PROFILE must be one of the ESP32BASE_PROFILE_* constants"
#endif

#ifndef ESP32BASE_ENABLE_LOG
#define ESP32BASE_ENABLE_LOG 1
#endif

#ifndef ESP32BASE_ENABLE_CONFIG
#define ESP32BASE_ENABLE_CONFIG 1
#endif

#ifndef ESP32BASE_ENABLE_SYSTEM
#define ESP32BASE_ENABLE_SYSTEM 1
#endif

#if ESP32BASE_PROFILE == ESP32BASE_PROFILE_RUNTIME
  #ifndef ESP32BASE_ENABLE_BUS
  #define ESP32BASE_ENABLE_BUS 1
  #endif
  #ifndef ESP32BASE_ENABLE_WATCHDOG
  #define ESP32BASE_ENABLE_WATCHDOG 1
  #endif
  #ifndef ESP32BASE_ENABLE_SLEEP
  #define ESP32BASE_ENABLE_SLEEP 1
  #endif
  #ifndef ESP32BASE_ENABLE_FS
  #define ESP32BASE_ENABLE_FS 1
  #endif
  #ifndef ESP32BASE_ENABLE_HEALTH
  #define ESP32BASE_ENABLE_HEALTH 1
  #endif
#elif ESP32BASE_PROFILE == ESP32BASE_PROFILE_NET
  #ifndef ESP32BASE_ENABLE_WIFI
  #define ESP32BASE_ENABLE_WIFI 1
  #endif
  #ifndef ESP32BASE_ENABLE_DNS
  #define ESP32BASE_ENABLE_DNS 1
  #endif
  #ifndef ESP32BASE_ENABLE_NTP
  #define ESP32BASE_ENABLE_NTP 1
  #endif
  #ifndef ESP32BASE_ENABLE_MDNS
  #define ESP32BASE_ENABLE_MDNS 1
  #endif
#elif ESP32BASE_PROFILE == ESP32BASE_PROFILE_NET_RUNTIME
  #ifndef ESP32BASE_ENABLE_BUS
  #define ESP32BASE_ENABLE_BUS 1
  #endif
  #ifndef ESP32BASE_ENABLE_WATCHDOG
  #define ESP32BASE_ENABLE_WATCHDOG 1
  #endif
  #ifndef ESP32BASE_ENABLE_SLEEP
  #define ESP32BASE_ENABLE_SLEEP 1
  #endif
  #ifndef ESP32BASE_ENABLE_FS
  #define ESP32BASE_ENABLE_FS 1
  #endif
  #ifndef ESP32BASE_ENABLE_HEALTH
  #define ESP32BASE_ENABLE_HEALTH 1
  #endif
  #ifndef ESP32BASE_ENABLE_WIFI
  #define ESP32BASE_ENABLE_WIFI 1
  #endif
  #ifndef ESP32BASE_ENABLE_DNS
  #define ESP32BASE_ENABLE_DNS 1
  #endif
  #ifndef ESP32BASE_ENABLE_NTP
  #define ESP32BASE_ENABLE_NTP 1
  #endif
  #ifndef ESP32BASE_ENABLE_MDNS
  #define ESP32BASE_ENABLE_MDNS 1
  #endif
#elif ESP32BASE_PROFILE == ESP32BASE_PROFILE_WEB
  #ifndef ESP32BASE_ENABLE_BUS
  #define ESP32BASE_ENABLE_BUS 1
  #endif
  #ifndef ESP32BASE_ENABLE_WIFI
  #define ESP32BASE_ENABLE_WIFI 1
  #endif
  #ifndef ESP32BASE_ENABLE_DNS
  #define ESP32BASE_ENABLE_DNS 1
  #endif
  #ifndef ESP32BASE_ENABLE_NTP
  #define ESP32BASE_ENABLE_NTP 1
  #endif
  #ifndef ESP32BASE_ENABLE_MDNS
  #define ESP32BASE_ENABLE_MDNS 1
  #endif
  #ifndef ESP32BASE_ENABLE_WEB
  #define ESP32BASE_ENABLE_WEB 1
  #endif
#elif ESP32BASE_PROFILE == ESP32BASE_PROFILE_WEB_RUNTIME
  #ifndef ESP32BASE_ENABLE_BUS
  #define ESP32BASE_ENABLE_BUS 1
  #endif
  #ifndef ESP32BASE_ENABLE_WATCHDOG
  #define ESP32BASE_ENABLE_WATCHDOG 1
  #endif
  #ifndef ESP32BASE_ENABLE_SLEEP
  #define ESP32BASE_ENABLE_SLEEP 1
  #endif
  #ifndef ESP32BASE_ENABLE_FS
  #define ESP32BASE_ENABLE_FS 1
  #endif
  #ifndef ESP32BASE_ENABLE_HEALTH
  #define ESP32BASE_ENABLE_HEALTH 1
  #endif
  #ifndef ESP32BASE_ENABLE_WIFI
  #define ESP32BASE_ENABLE_WIFI 1
  #endif
  #ifndef ESP32BASE_ENABLE_DNS
  #define ESP32BASE_ENABLE_DNS 1
  #endif
  #ifndef ESP32BASE_ENABLE_NTP
  #define ESP32BASE_ENABLE_NTP 1
  #endif
  #ifndef ESP32BASE_ENABLE_MDNS
  #define ESP32BASE_ENABLE_MDNS 1
  #endif
  #ifndef ESP32BASE_ENABLE_WEB
  #define ESP32BASE_ENABLE_WEB 1
  #endif
#elif ESP32BASE_PROFILE == ESP32BASE_PROFILE_FULL
  #ifndef ESP32BASE_ENABLE_BUS
  #define ESP32BASE_ENABLE_BUS 1
  #endif
  #ifndef ESP32BASE_ENABLE_WATCHDOG
  #define ESP32BASE_ENABLE_WATCHDOG 1
  #endif
  #ifndef ESP32BASE_ENABLE_SLEEP
  #define ESP32BASE_ENABLE_SLEEP 1
  #endif
  #ifndef ESP32BASE_ENABLE_FS
  #define ESP32BASE_ENABLE_FS 1
  #endif
  #ifndef ESP32BASE_ENABLE_HEALTH
  #define ESP32BASE_ENABLE_HEALTH 1
  #endif
  #ifndef ESP32BASE_ENABLE_WIFI
  #define ESP32BASE_ENABLE_WIFI 1
  #endif
  #ifndef ESP32BASE_ENABLE_DNS
  #define ESP32BASE_ENABLE_DNS 1
  #endif
  #ifndef ESP32BASE_ENABLE_NTP
  #define ESP32BASE_ENABLE_NTP 1
  #endif
  #ifndef ESP32BASE_ENABLE_MDNS
  #define ESP32BASE_ENABLE_MDNS 1
  #endif
  #ifndef ESP32BASE_ENABLE_WEB
  #define ESP32BASE_ENABLE_WEB 1
  #endif
  #ifndef ESP32BASE_ENABLE_OTA
  #define ESP32BASE_ENABLE_OTA 1
  #endif
  #ifndef ESP32BASE_ENABLE_WEB_OTA
  #define ESP32BASE_ENABLE_WEB_OTA 1
  #endif
#endif

#ifndef ESP32BASE_ENABLE_BUS
#define ESP32BASE_ENABLE_BUS 0
#endif
#ifndef ESP32BASE_ENABLE_WATCHDOG
#define ESP32BASE_ENABLE_WATCHDOG 0
#endif
#ifndef ESP32BASE_ENABLE_SLEEP
#define ESP32BASE_ENABLE_SLEEP 0
#endif
#ifndef ESP32BASE_ENABLE_FS
#define ESP32BASE_ENABLE_FS 0
#endif
#ifndef ESP32BASE_ENABLE_FILELOG
#if ESP32BASE_ENABLE_FS
#define ESP32BASE_ENABLE_FILELOG 1
#else
#define ESP32BASE_ENABLE_FILELOG 0
#endif
#endif
#ifndef ESP32BASE_ENABLE_HEALTH
#define ESP32BASE_ENABLE_HEALTH 0
#endif
#ifndef ESP32BASE_ENABLE_WIFI
#define ESP32BASE_ENABLE_WIFI 0
#endif
#ifndef ESP32BASE_ENABLE_DNS
#define ESP32BASE_ENABLE_DNS 0
#endif
#ifndef ESP32BASE_ENABLE_NTP
#define ESP32BASE_ENABLE_NTP 0
#endif
#ifndef ESP32BASE_ENABLE_MDNS
#define ESP32BASE_ENABLE_MDNS 0
#endif
#ifndef ESP32BASE_ENABLE_WEB
#define ESP32BASE_ENABLE_WEB 0
#endif
#ifndef ESP32BASE_ENABLE_OTA
#define ESP32BASE_ENABLE_OTA 0
#endif
#ifndef ESP32BASE_ENABLE_WEB_OTA
#define ESP32BASE_ENABLE_WEB_OTA 0
#endif
#ifndef ESP32BASE_ENABLE_ARDUINO_OTA
#define ESP32BASE_ENABLE_ARDUINO_OTA ESP32BASE_ENABLE_OTA
#endif

#if ESP32BASE_ENABLE_WEB && !ESP32BASE_ENABLE_WIFI
#error "ESP32BASE_ENABLE_WEB requires ESP32BASE_ENABLE_WIFI"
#endif
#if ESP32BASE_ENABLE_OTA && (!ESP32BASE_ENABLE_WIFI || !ESP32BASE_ENABLE_WEB)
#error "ESP32BASE_ENABLE_OTA requires ESP32BASE_ENABLE_WIFI and ESP32BASE_ENABLE_WEB"
#endif
#if ESP32BASE_ENABLE_WEB_OTA && (!ESP32BASE_ENABLE_WEB || !ESP32BASE_ENABLE_OTA)
#error "ESP32BASE_ENABLE_WEB_OTA requires ESP32BASE_ENABLE_WEB and ESP32BASE_ENABLE_OTA"
#endif
#if ESP32BASE_ENABLE_ARDUINO_OTA && !ESP32BASE_ENABLE_OTA
#error "ESP32BASE_ENABLE_ARDUINO_OTA requires ESP32BASE_ENABLE_OTA"
#endif
#if ESP32BASE_ENABLE_FILELOG && !ESP32BASE_ENABLE_FS
#error "ESP32BASE_ENABLE_FILELOG requires ESP32BASE_ENABLE_FS"
#endif
#if ESP32BASE_ENABLE_DNS && !ESP32BASE_ENABLE_WIFI
#error "ESP32BASE_ENABLE_DNS requires ESP32BASE_ENABLE_WIFI"
#endif
#if ESP32BASE_ENABLE_NTP && !ESP32BASE_ENABLE_WIFI
#error "ESP32BASE_ENABLE_NTP requires ESP32BASE_ENABLE_WIFI"
#endif
#if ESP32BASE_ENABLE_MDNS && !ESP32BASE_ENABLE_WIFI
#error "ESP32BASE_ENABLE_MDNS requires ESP32BASE_ENABLE_WIFI"
#endif
